cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/DoubleMuon_2022C/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon_2022C/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon_2022D/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon_2022E/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon_2022F/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon_2022G/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon0_2023C_v1/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon0_2023C_v2/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon0_2023C_v3/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon0_2023C_v4/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon1_2023C_v1/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon1_2023C_v2/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon1_2023C_v3/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon1_2023C_v4/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon0_2023D_v1/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon0_2023D_v2/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon1_2023D_v1/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon1_2023D_v2/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon0_2024B/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon0_2024C/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon0_2024D/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon0_2024E_v1/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon0_2024E_v2/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon0_2024F/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon0_2024G/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon0_2024H/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon0_2024I_v1/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon0_2024I_v2/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon1_2024B/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon1_2024C/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon1_2024D/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon1_2024E_v1/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon1_2024E_v2/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon1_2024F/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon1_2024G/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon1_2024H/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon1_2024I_v1/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/Muon1_2024I_v2/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/DY50to120_Summer22/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/DY120to200_Summer22/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/EWK_2L2J_Summer22/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/TTto2L2Nu_Summer22/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/TTtoLNu2Q_Summer22/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/TWminusto2L2Nu_Summer22/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WZto2L2Q_Summer22/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WZto3LNu_Summer22/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZto2L2Nu_Summer22/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZto2L2Q_Summer22/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZto4L_Summer22/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WWto2L2Nu_Summer22/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZZ_Summer22/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WZZ_Summer22/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WWZ_4F_Summer22/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WWW_4F_Summer22/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/DY50to120_Summer22EE/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/DY120to200_Summer22EE/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/EWK_2L2J_Summer22EE/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/TTto2L2Nu_Summer22EE/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/TTtoLNu2Q_Summer22EE/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/TWminusto2L2Nu_Summer22EE/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WZto2L2Q_Summer22EE/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WZto3LNu_Summer22EE/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZto2L2Nu_Summer22EE/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZto2L2Q_Summer22EE/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZto4L_Summer22EE/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WWto2L2Nu_Summer22EE/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZZ_Summer22EE/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WZZ_Summer22EE/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WWZ_4F_Summer22EE/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WWW_4F_Summer22EE/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/DY50to120_Summer23/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/DY120to200_Summer23/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/EWK_2L2J_Summer23/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/TTto2L2Nu_Summer23/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/TTtoLNu2Q_Summer23/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/TWminusto2L2Nu_Summer23/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WZto2L2Q_Summer23/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WZto3LNu_Summer23/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZto2L2Nu_Summer23/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZto2L2Q_Summer23/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZto4L_Summer23/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WWto2L2Nu_Summer23/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZZ_Summer23/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WZZ_Summer23/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WWZ_4F_Summer23/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WWW_4F_Summer23/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/DY50to120_Summer23BPix/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/DY120to200_Summer23BPix/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/EWK_2L2J_Summer23BPix/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/TTto2L2Nu_Summer23BPix/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/TTtoLNu2Q_Summer23BPix/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/TWminusto2L2Nu_Summer23BPix/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WZto2L2Q_Summer23BPix/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WZto3LNu_Summer23BPix/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZto2L2Nu_Summer23BPix/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZto2L2Q_Summer23BPix/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZto4L_Summer23BPix/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WWto2L2Nu_Summer23BPix/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZZ_Summer23BPix/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WZZ_Summer23BPix/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WWZ_4F_Summer23BPix/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WWW_4F_Summer23BPix/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/DY50to120_Summer24/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/TTtoLNu2Q_Summer24/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WZto2L2Q_Summer24/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WZto3LNu_Summer24/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZto2L2Nu_Summer24/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/ZZto2L2Q_Summer24/
condor_submit task.jdl
cd /afs/cern.ch/user/y/yulou/CMSSW_14_0_14/src/HToMuMu/histos/WWto2L2Nu_Summer24/
condor_submit task.jdl
